// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spotilove;

#nullable disable

namespace JsonDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526094229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spotilove.Like", b =>
                {
                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLike")
                        .HasColumnType("boolean")
                        .HasColumnName("is_like");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("is_match");

                    b.HasKey("FromUserId", "ToUserId")
                        .HasName("pk_likes");

                    b.HasIndex("ToUserId")
                        .HasDatabaseName("ix_likes_to_user_id");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Spotilove.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_messages_from_user_id");

                    b.HasIndex("ToUserId")
                        .HasDatabaseName("ix_messages_to_user_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Spotilove.MusicProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FavoriteArtists")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("favorite_artists");

                    b.Property<string>("FavoriteGenres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("favorite_genres");

                    b.Property<string>("FavoriteSongs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("favorite_songs");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_music_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_music_profiles_user_id");

                    b.ToTable("music_profiles", (string)null);
                });

            modelBuilder.Entity("Spotilove.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SexualOrientation")
                        .HasColumnType("text")
                        .HasColumnName("sexual_orientation");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Spotilove.UserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_images");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_images_user_id");

                    b.ToTable("user_images", (string)null);
                });

            modelBuilder.Entity("Spotilove.UserSuggestionQueue", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SuggestedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_user_id");

                    b.Property<double>("CompatibilityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("compatibility_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("integer")
                        .HasColumnName("queue_position");

                    b.HasKey("UserId", "SuggestedUserId")
                        .HasName("pk_user_suggestion_queues");

                    b.HasIndex("SuggestedUserId")
                        .HasDatabaseName("ix_user_suggestion_queues_suggested_user_id");

                    b.ToTable("user_suggestion_queues", (string)null);
                });

            modelBuilder.Entity("Spotilove.Like", b =>
                {
                    b.HasOne("Spotilove.User", "FromUser")
                        .WithMany("LikesSent")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_users_from_user_id");

                    b.HasOne("Spotilove.User", "ToUser")
                        .WithMany("LikesReceived")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_users_to_user_id");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Spotilove.Message", b =>
                {
                    b.HasOne("Spotilove.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_from_user_id");

                    b.HasOne("Spotilove.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_to_user_id");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Spotilove.MusicProfile", b =>
                {
                    b.HasOne("Spotilove.User", "User")
                        .WithOne("MusicProfile")
                        .HasForeignKey("Spotilove.MusicProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_music_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spotilove.UserImage", b =>
                {
                    b.HasOne("Spotilove.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_images_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spotilove.UserSuggestionQueue", b =>
                {
                    b.HasOne("Spotilove.User", "SuggestedUser")
                        .WithMany()
                        .HasForeignKey("SuggestedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_suggestion_queues_users_suggested_user_id");

                    b.HasOne("Spotilove.User", "User")
                        .WithMany("Suggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_suggestion_queues_users_user_id");

                    b.Navigation("SuggestedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spotilove.User", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LikesReceived");

                    b.Navigation("LikesSent");

                    b.Navigation("MusicProfile");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
